# Vagrantfile

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/mantic64"
    
    
    config.vm.provider "virtualbox" do |vb|
      vb.memory = 1024 # 1 GB RAM
    end
  
    config.vm.network "private_network", ip: "192.168.33.10" # You can change this IP address if needed
  
    config.vm.provision "shell", inline: <<-SHELL
      # Update and install necessary dependencies
      sudo apt-get update -y
      sudo apt install mysql-server -y
    SHELL
  end
  