Vagrant.configure("2") do |config|
    config.vm.box = "fedora/38-cloud-base"
    config.vm.box_version = "38.20230413.1"
  
    config.vm.define "fedora_base_38" do |fedora|
      fedora.vm.network "public_network"
  
      fedora.vm.provider "virtualbox" do |vb|
        vb.memory = "2048" # Set desired memory size
        vb.cpus = 2       # Set desired CPU count
        vb.gui = false    # Disable GUI
      end
  
      fedora.vm.boot_timeout = 900 # Set timeout to 10 minutes (default is 300 seconds)
  
      fedora.vm.provision "shell", inline: <<-SHELL
        sudo dnf update -y   # Apply any available package updates
      SHELL
    end
  
    # Add any additional configurations you may need below this line
  
  end
  