# Creating Sample vagrant file that creates 7 VMs using virtualbox.  Before running "vagrant up", I already installed the disksize plugin (vagrant plugin install vagrant-disksize)

Vagrant.configure("2") do |config|
  
  # Define host1 machine
  config.vm.define "host1" do |host1|
    host1.vm.box = "generic/fedora37"
    host1.vm.hostname = "host1"
    host1.disksize.size = "60GB"
    host1.vm.boot_timeout = 300
    host1.vm.provider "virtualbox" do |vmware|
      vmware.memory = 4096
      vmware.cpus = 2
    end
  end

  # Define sql machine
  config.vm.define "sql" do |sql|
    sql.vm.box = "generic/fedora37"
    sql.vm.hostname = "sql"
    sql.disksize.size = "60GB"
    sql.vm.boot_timeout = 300
    sql.vm.provider "virtualbox" do |vmware|
      vmware.memory = 4096
      vmware.cpus = 2
    end
  end

  # Define fedora1 machine
  config.vm.define "babygirl3" do |babygirl3|
    babygirl3.vm.box = "generic/fedora37"
    babygirl3.vm.hostname = "babygirl3"
    babygirl3.disksize.size = "60GB"
    babygirl3.vm.boot_timeout = 300
    babygirl3.vm.provider "virtualbox" do |vmware|
      vmware.memory = 4096
      vmware.cpus = 2
    end
  end
end
