# Vagrantfile

Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-20.04"
    
    
    config.vm.provider "virtualbox" do |vb|
      vb.memory = 4096 # 4 GB RAM
    end
  
    config.vm.network "private_network", ip: "192.168.33.10" # You can change this IP address if needed
  
    config.vm.provision "shell", inline: <<-SHELL
      # Update and install necessary dependencies
      sudo apt-get update
      sudo apt-get install -y curl openssh-server ca-certificates tzdata perl
  
      # Install Postfix
      sudo DEBIAN_FRONTEND=noninteractive apt-get install -y postfix
  
      # Accept defaults during Postfix installation
      echo "postfix postfix/main_mailer_type select Internet Site" | sudo debconf-set-selections
      echo "postfix postfix/mailname string example.com" | sudo debconf-set-selections
  
      # Add GitLab package repository and install GitLab
      curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh | sudo bash
      sudo apt-get install gitlab-ee
    SHELL
  end
  