Vagrant.configure("2") do |config|
  config.vm.define "LampServer" do |lampsrv|
    lampsrv.vm.box = "ubuntu/focal64" # Ubuntu 20.04.6

    lampsrv.vm.network "public_network"

    lampsrv.vm.provider "virtualbox" do |vb|
      vb.memory = "2048" # Set desired memory size
      vb.cpus = 2       # Set desired CPU count
      vb.gui = false    # Disable GUI
    end

    lampsrv.ssh.username = "cliffgoat" # Set the desired default username

    lampsrv.vm.boot_timeout = 600 # Set timeout to 10 minutes (default is 300 seconds)

    lampsrv.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get upgrade -y   # Apply any available package updates

      sudo apt-get install -y apache2
      sudo apt-get install -y mysql-server
      sudo apt-get install -y php libapache2-mod-php php-mysql

      # Optional: Set up a MySQL user and database
      # sudo mysql -e "CREATE DATABASE my_database;"
      # sudo mysql -e "CREATE USER 'my_user'@'localhost' IDENTIFIED BY 'my_password';"
      # sudo mysql -e "GRANT ALL PRIVILEGES ON my_database.* TO 'my_user'@'localhost';"
      # sudo mysql -e "FLUSH PRIVILEGES;"

      sudo systemctl restart apache2

      # Copy files to /var/www/html/
      sudo cp /vagrant/index.html /var/www/html/index.html
      sudo cp /vagrant/process.php /var/www/html/process.php
      sudo cp /vagrant/create_table.sql /var/www/html/create_table.sql
    SHELL
  end
end
